import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, dirname, relative } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * FIX-19: Generate embedded assets JSON for BRAT self-provisioning.
 * Scans the same sources as vault-deploy: workers, bundled-skills, templates.
 * Assets are extracted at runtime by AssetProvisioner if missing from plugin dir.
 */
function generateEmbeddedAssets() {
    const assets = {};
    let workerCount = 0, skillCount = 0, templateCount = 0, wasmCount = 0;

    // Workers (built by previous esbuild steps)
    for (const worker of ["sandbox-worker.js", "mcp-server-worker.js"]) {
        if (existsSync(worker)) {
            assets[worker] = readFileSync(worker, "utf-8");
            workerCount++;
        }
    }

    // Bundled skills (scan directory -- new skills are picked up automatically)
    const bundledSkillsDir = join(__dirname, "bundled-skills");
    if (existsSync(bundledSkillsDir)) {
        for (const skillDir of readdirSync(bundledSkillsDir)) {
            const srcDir = join(bundledSkillsDir, skillDir);
            if (!statSync(srcDir).isDirectory()) continue;
            for (const file of readdirSync(srcDir)) {
                if (file.startsWith('.')) continue; // AUDIT-010 L-1: skip dotfiles (.DS_Store etc.)
                const filePath = join(srcDir, file);
                if (statSync(filePath).isDirectory()) continue;
                assets[`skills/${skillDir}/${file}`] = readFileSync(filePath, "utf-8");
                skillCount++;
            }
        }
    }

    // PPTX templates (binary -- base64 encoded with prefix)
    const templatesSrc = join(__dirname, "assets/templates");
    if (existsSync(templatesSrc)) {
        for (const f of readdirSync(templatesSrc).filter(f => f.endsWith(".pptx"))) {
            assets[`templates/${f}`] = "base64:" + readFileSync(join(templatesSrc, f)).toString("base64");
            templateCount++;
        }
    }

    // WASM runtime binaries -- FIX-22: full self-contained install for BRAT.
    // Without these, BRAT users hit ENOENT on KnowledgeDB.open() and reranker
    // falls through to unreliable HF CDN (cas-bridge.xethub.hf.co ERR_CONTENT_LENGTH_MISMATCH).
    // Total footprint: ~13 MB raw, ~17 MB base64.
    const wasmSources = [
        { src: "node_modules/sql.js/dist/sql-wasm.wasm", dest: "sql-wasm.wasm" },
        { src: "node_modules/sql.js/dist/sql-wasm-browser.wasm", dest: "sql-wasm-browser.wasm" },
        { src: "node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm", dest: "ort-wasm-simd-threaded.wasm" },
        { src: "node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.mjs", dest: "ort-wasm-simd-threaded.mjs" },
    ];
    for (const { src, dest } of wasmSources) {
        const abs = join(__dirname, src);
        if (!existsSync(abs)) {
            throw new Error(`[embed-assets] FATAL: Required WASM asset not found: ${src}. Run npm install.`);
        }
        if (dest.endsWith(".wasm")) {
            assets[dest] = "base64:" + readFileSync(abs).toString("base64");
        } else {
            // .mjs is text
            assets[dest] = readFileSync(abs, "utf-8");
        }
        wasmCount++;
    }

    // Validate: workers are mandatory
    if (workerCount === 0) {
        throw new Error("[embed-assets] FATAL: No worker files found. Build workers before main.");
    }

    // Write generated file
    const outDir = join(__dirname, "src/_generated");
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
    const json = JSON.stringify(assets);

    // Safety: abort if generated file is suspiciously large.
    // Current footprint (FIX-22): ~17 MB with WASM. Limit at 25 MB gives headroom
    // for additional bundled skills/templates without hiding genuine bloat.
    const MAX_EMBED_BYTES = 25 * 1024 * 1024;
    if (json.length > MAX_EMBED_BYTES) {
        throw new Error(`[embed-assets] FATAL: Generated assets too large (${(json.length / 1024 / 1024).toFixed(1)}MB, limit ${MAX_EMBED_BYTES / 1024 / 1024}MB). Review wasmSources or raise the limit deliberately.`);
    }

    writeFileSync(join(outDir, "embedded-assets.json"), json);
    console.log(`[embed-assets] Embedded ${workerCount} workers, ${skillCount} skills, ${templateCount} templates, ${wasmCount} WASM (${(json.length / 1024 / 1024).toFixed(1)}MB)`);
}

// Path to the Obsidian vault plugin folder (auto-deploy on build)
// Set PLUGIN_DIR in your .env or shell environment
// Load .env file if it exists (for PLUGIN_DIR with iCloud paths containing spaces)
try {
    const envContent = readFileSync(join(__dirname, '.env'), 'utf-8');
    for (const line of envContent.split('\n')) {
        const match = line.match(/^([A-Z_]+)=(.*)$/);
        if (match && !process.env[match[1]]) {
            // Strip surrounding quotes (single or double) from .env values
            process.env[match[1]] = match[2].trim().replace(/^["']|["']$/g, '');
        }
    }
} catch { /* .env not found — use shell environment */ }
const VAULT_PLUGIN_DIR = process.env.PLUGIN_DIR || "";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [
        {
            // Resolve "node:xyz" imports → mark them external (Electron provides them)
            name: "node-builtins",
            setup(build) {
                build.onResolve({ filter: /^node:/ }, (args) => ({
                    path: args.path,
                    external: true,
                }));
            }
        },
        {
            // Force transformers.js to use the web ONNX backend in Electron.
            // Electron's renderer is detected as IS_NODE_ENV=true, which selects
            // onnxruntime-node (native addon that can't load). Patching to false
            // makes it take the web branch with proper device registration.
            name: "force-onnx-web-backend",
            setup(build) {
                build.onResolve({ filter: /backends\/onnx\.js/ }, (args) => {
                    if (!args.path.includes('onnx')) return;
                    return { path: args.path, pluginData: { patch: true }, namespace: 'file' };
                });
                // Fallback: post-process the bundle to patch IS_NODE_ENV
                build.onEnd(() => {
                    const outfile = 'main.js';
                    if (!existsSync(outfile)) return;
                    let code = readFileSync(outfile, 'utf-8');
                    const marker = '} else if (apis.IS_NODE_ENV) {';
                    if (code.includes(marker)) {
                        code = code.replace(marker, '} else if (false /* patched: force web backend in Electron */) {');
                        writeFileSync(outfile, code);
                        console.log('[force-onnx-web-backend] Patched IS_NODE_ENV in main.js');
                    }
                });
            }
        },
        {
            // Embed TypeScript source into the bundle for core self-modification (Phase 4).
            // Only active for production builds. Source files are base64-encoded and injected
            // as a global constant `EMBEDDED_SOURCE` that EmbeddedSourceManager reads at runtime.
            name: "embed-source",
            setup(build) {
                if (!prod) return; // Only embed source in production builds

                build.onEnd((result) => {
                    if (result.errors.length > 0) return; // Skip on build errors

                    try {
                        const srcDir = join(__dirname, "src");
                        const files = {};

                        function walkDir(dir) {
                            const entries = readdirSync(dir);
                            for (const entry of entries) {
                                const fullPath = join(dir, entry);
                                const stat = statSync(fullPath);
                                if (stat.isDirectory()) {
                                    // Skip test directories and node_modules
                                    if (entry === "node_modules" || entry === "__tests__" || entry === "test") continue;
                                    walkDir(fullPath);
                                } else if (entry.endsWith(".ts") || entry.endsWith(".tsx")) {
                                    const relPath = "src/" + relative(srcDir, fullPath).replace(/\\/g, "/");
                                    const content = readFileSync(fullPath, "utf-8");
                                    // Base64-encode to avoid escaping issues
                                    files[relPath] = Buffer.from(content).toString("base64");
                                }
                            }
                        }
                        walkDir(srcDir);

                        const pkg = JSON.parse(readFileSync(join(__dirname, "package.json"), "utf-8"));
                        const embedded = {
                            version: pkg.version || "0.0.0",
                            files,
                            buildConfig: {
                                format: "cjs",
                                target: "es2022",
                                external: [
                                    "obsidian", "electron",
                                    "@codemirror/autocomplete", "@codemirror/collab",
                                    "@codemirror/commands", "@codemirror/language",
                                    "@codemirror/lint", "@codemirror/search",
                                    "@codemirror/state", "@codemirror/view",
                                    "@lezer/common", "@lezer/highlight", "@lezer/lr",
                                ],
                            },
                        };

                        // Read the generated main.js and prepend the embedded source constant
                        const outfile = "main.js";
                        if (existsSync(outfile)) {
                            const mainJs = readFileSync(outfile, "utf-8");
                            const injection = `\nvar EMBEDDED_SOURCE = ${JSON.stringify(embedded)};\n`;
                            // Insert after the banner comment
                            const bannerEnd = mainJs.indexOf("*/");
                            if (bannerEnd !== -1) {
                                const patched = mainJs.slice(0, bannerEnd + 2) + injection + mainJs.slice(bannerEnd + 2);
                                writeFileSync(outfile, patched);
                            } else {
                                writeFileSync(outfile, injection + mainJs);
                            }

                            const fileCount = Object.keys(files).length;
                            const sizeKB = Math.round(JSON.stringify(embedded).length / 1024);
                            console.log(`[embed-source] Embedded ${fileCount} source files (~${sizeKB}KB)`);
                        }
                    } catch (e) {
                        console.warn("[embed-source] Failed to embed source:", e.message);
                    }
                });
            }
        },
        {
            name: "vault-deploy",
            setup(build) {
                build.onEnd(() => {
                    if (existsSync(VAULT_PLUGIN_DIR)) {
                        try {
                            copyFileSync("main.js", `${VAULT_PLUGIN_DIR}/main.js`);
                            copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
                            const logoSrc = join(__dirname, "src/assets/logo.png");
                            if (existsSync(logoSrc)) {
                                copyFileSync(logoSrc, `${VAULT_PLUGIN_DIR}/logo.png`);
                            }
                            if (existsSync("sandbox-worker.js")) {
                                copyFileSync("sandbox-worker.js", `${VAULT_PLUGIN_DIR}/sandbox-worker.js`);
                            }
                            if (existsSync("mcp-server-worker.js")) {
                                copyFileSync("mcp-server-worker.js", `${VAULT_PLUGIN_DIR}/mcp-server-worker.js`);
                            }
                            // Copy sql.js WASM binaries for Knowledge DB
                            // sql.js may request either sql-wasm.wasm or sql-wasm-browser.wasm
                            // depending on which variant esbuild resolves
                            for (const wasmName of ["sql-wasm.wasm", "sql-wasm-browser.wasm"]) {
                                const wasmSrc = join(__dirname, "node_modules/sql.js/dist", wasmName);
                                if (existsSync(wasmSrc)) {
                                    copyFileSync(wasmSrc, `${VAULT_PLUGIN_DIR}/${wasmName}`);
                                }
                            }
                            // Copy ONNX Runtime WASM binaries for Reranker (transformers.js)
                            for (const ortFile of ["ort-wasm-simd-threaded.wasm", "ort-wasm-simd-threaded.mjs"]) {
                                const ortSrc = join(__dirname, "node_modules/onnxruntime-web/dist", ortFile);
                                if (existsSync(ortSrc)) {
                                    copyFileSync(ortSrc, `${VAULT_PLUGIN_DIR}/${ortFile}`);
                                }
                            }
                            // Copy bundled skills to plugin skills directory
                            const bundledSkillsDir = join(__dirname, "bundled-skills");
                            if (existsSync(bundledSkillsDir)) {
                                const skillDirs = readdirSync(bundledSkillsDir);
                                for (const skillDir of skillDirs) {
                                    const srcDir = join(bundledSkillsDir, skillDir);
                                    if (!statSync(srcDir).isDirectory()) continue;
                                    const destDir = `${VAULT_PLUGIN_DIR}/skills/${skillDir}`;
                                    if (!existsSync(destDir)) mkdirSync(destDir, { recursive: true });
                                    const files = readdirSync(srcDir);
                                    for (const file of files) {
                                        copyFileSync(join(srcDir, file), join(destDir, file));
                                    }
                                }
                                console.log(`[vault-deploy] Copied ${skillDirs.length} bundled skill(s)`);
                            }
                            // Copy default PPTX templates
                            const templatesSrc = join(__dirname, "assets/templates");
                            if (existsSync(templatesSrc)) {
                                const templatesDir = `${VAULT_PLUGIN_DIR}/templates`;
                                if (!existsSync(templatesDir)) mkdirSync(templatesDir, { recursive: true });
                                const templateFiles = readdirSync(templatesSrc).filter(f => f.endsWith('.pptx'));
                                for (const f of templateFiles) {
                                    copyFileSync(join(templatesSrc, f), join(templatesDir, f));
                                }
                                if (templateFiles.length > 0) {
                                    console.log(`[vault-deploy] Copied ${templateFiles.length} PPTX template(s)`);
                                }
                            }
                            console.log(`[vault-deploy] → ${VAULT_PLUGIN_DIR}`);
                        } catch (e) {
                            console.warn("[vault-deploy] Copy failed:", e.message);
                        }
                    }
                });
            }
        }
    ],
});

// Sandbox worker — separate OS process (ADR-021)
const workerContext = await esbuild.context({
    entryPoints: ["src/core/sandbox/sandbox-worker.ts"],
    bundle: true,
    external: [],        // Standalone Node.js, no externals needed
    platform: "node",
    format: "cjs",
    target: "es2022",
    outfile: "sandbox-worker.js",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
});

// MCP Server worker — separate OS process (ADR-053)
const mcpWorkerContext = await esbuild.context({
    entryPoints: ["src/mcp/mcp-server-worker.ts"],
    bundle: true,
    external: [],        // Standalone Node.js, bundled with MCP SDK
    platform: "node",
    format: "cjs",
    target: "es2022",
    outfile: "mcp-server-worker.js",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
});

if (prod) {
    // Workers first — vault-deploy (main's onEnd) copies worker files
    await workerContext.rebuild();
    await mcpWorkerContext.rebuild();
    // FIX-19: Embed runtime assets into main.js for BRAT self-provisioning
    generateEmbeddedAssets();
    await context.rebuild();
    process.exit(0);
} else {
    // FIX-19: Generate initial embedded assets for watch mode (workers may not exist yet)
    try { generateEmbeddedAssets(); } catch { /* workers not yet built — will be generated on first rebuild */ }
    await context.watch();
    await workerContext.watch();
    await mcpWorkerContext.watch();
}
