import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, dirname, relative } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");


/**
 * Phase 1: Replacement for generateEmbeddedAssets that emits separate
 * TypeScript const files instead of a single JSON blob. Readers import
 * the specific const they need, esbuild tree-shakes the rest.
 *
 * Emits four files under src/_generated/:
 *   - bundled-workers.ts        worker source as strings
 *   - bundled-skills.ts         skill markdown as nested Record
 *   - bundled-templates.ts      PPTX (base64) + note templates (text)
 *   - bundled-wasm.ts           sql.js + ONNX WASM as base64
 *
 * Runs alongside generateEmbeddedAssets during migration. Both stay in
 * sync until all readers have been switched off the AssetProvisioner.
 */
function generateInlineAssets() {
    const outDir = join(__dirname, "src/_generated");
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

    // ---- Workers --------------------------------------------------------
    const workers = {};
    for (const w of ["sandbox-worker.js", "mcp-server-worker.js"]) {
        if (existsSync(w)) workers[w] = readFileSync(w, "utf-8");
    }
    if (Object.keys(workers).length === 0) {
        throw new Error("[inline-assets] FATAL: No worker files found. Build workers before main.");
    }
    const workerLines = [
        "// AUTO-GENERATED -- do not edit. Source: esbuild.config.mjs generateInlineAssets().",
        "/* eslint-disable */",
        "",
    ];
    for (const [name, src] of Object.entries(workers)) {
        const constName = name === "sandbox-worker.js" ? "SANDBOX_WORKER_CODE" : "MCP_WORKER_CODE";
        workerLines.push(`export const ${constName} = ${JSON.stringify(src)};`);
    }
    writeFileSync(join(outDir, "bundled-workers.ts"), workerLines.join("\n") + "\n");

    // ---- Skills ---------------------------------------------------------
    const skills = {};
    let skillCount = 0;
    const bundledSkillsDir = join(__dirname, "bundled-skills");
    if (existsSync(bundledSkillsDir)) {
        for (const skillDir of readdirSync(bundledSkillsDir)) {
            const srcDir = join(bundledSkillsDir, skillDir);
            if (!statSync(srcDir).isDirectory()) continue;
            const files = {};
            for (const file of readdirSync(srcDir)) {
                if (file.startsWith('.')) continue;
                const filePath = join(srcDir, file);
                if (statSync(filePath).isDirectory()) continue;
                files[file] = readFileSync(filePath, "utf-8");
                skillCount++;
            }
            if (Object.keys(files).length > 0) skills[skillDir] = files;
        }
    }
    writeFileSync(
        join(outDir, "bundled-skills.ts"),
        [
            "// AUTO-GENERATED -- do not edit. Source: esbuild.config.mjs generateInlineAssets().",
            "/* eslint-disable */",
            "",
            "export const BUNDLED_SKILLS: Record<string, Record<string, string>> = " + JSON.stringify(skills, null, 2) + ";",
            "",
        ].join("\n"),
    );

    // ---- Templates ------------------------------------------------------
    const pptxTemplates = {};
    let pptxCount = 0;
    const templatesSrc = join(__dirname, "assets/templates");
    if (existsSync(templatesSrc)) {
        for (const f of readdirSync(templatesSrc).filter(f => f.endsWith(".pptx"))) {
            // strip the .pptx extension and the "default-" prefix so keys match TemplateCatalog themeNames
            const themeKey = f.replace(/^default-/, "").replace(/\.pptx$/, "");
            pptxTemplates[themeKey] = readFileSync(join(templatesSrc, f)).toString("base64");
            pptxCount++;
        }
    }
    const noteTemplates = {};
    let noteCount = 0;
    const noteTemplatesSrc = join(__dirname, "bundled-templates/notes");
    if (existsSync(noteTemplatesSrc)) {
        for (const f of readdirSync(noteTemplatesSrc).filter(f => f.endsWith(".md"))) {
            noteTemplates[f] = readFileSync(join(noteTemplatesSrc, f), "utf-8");
            noteCount++;
        }
    }
    writeFileSync(
        join(outDir, "bundled-templates.ts"),
        [
            "// AUTO-GENERATED -- do not edit. Source: esbuild.config.mjs generateInlineAssets().",
            "/* eslint-disable */",
            "",
            "/** Themed PPTX templates, base64 encoded. Keys are themeName (e.g. 'minimal', 'modern'). */",
            "export const PPTX_TEMPLATES_BASE64: Record<string, string> = " + JSON.stringify(pptxTemplates, null, 2) + ";",
            "",
            "/** Note templates (markdown) used by /ingest, /ingest-deep, /meeting-summary. */",
            "export const NOTE_TEMPLATES: Record<string, string> = " + JSON.stringify(noteTemplates, null, 2) + ";",
            "",
        ].join("\n"),
    );

    // ---- WASM ----------------------------------------------------------
    // ONNX (12 MB) is NOT inlined anymore -- it ships as an optional
    // download from the plugin's GitHub release, see OptionalAssetManager.
    //
    // We deliberately ship ONLY the standard sql.js WASM build. The
    // browser-specific variant (sql-wasm-browser.wasm, ~860 KB) used to
    // be inlined alongside but was never imported by any reader and
    // simply added 860 KB to main.js -- dropping it brings us closer to
    // the 5 MB Obsidian-Sync ceiling.
    const wasmBlobs = {
        SQL_WASM_BASE64: { src: "node_modules/sql.js/dist/sql-wasm.wasm", kind: "binary" },
    };
    const wasmLines = [
        "// AUTO-GENERATED -- do not edit. Source: esbuild.config.mjs generateInlineAssets().",
        "/* eslint-disable */",
        "",
    ];
    for (const [constName, { src, kind }] of Object.entries(wasmBlobs)) {
        const abs = join(__dirname, src);
        if (!existsSync(abs)) {
            throw new Error(`[inline-assets] FATAL: Required asset not found: ${src}. Run npm install.`);
        }
        const value = kind === "binary"
            ? readFileSync(abs).toString("base64")
            : readFileSync(abs, "utf-8");
        wasmLines.push(`export const ${constName} = ${JSON.stringify(value)};`);
    }
    writeFileSync(join(outDir, "bundled-wasm.ts"), wasmLines.join("\n") + "\n");

    const workersN = Object.keys(workers).length;
    const wasmN = Object.keys(wasmBlobs).length;
    console.log(`[inline-assets] Emitted ${workersN} workers, ${skillCount} skills, ${pptxCount} PPTX templates, ${noteCount} note templates, ${wasmN} WASM as TS consts`);
}

/**
 * Generate plugin-source.json (optional asset for Self-Development) and
 * src/_generated/source-hash.ts (SHA256 of the JSON, bundled into
 * main.js so EmbeddedSourceManager can verify the downloaded file).
 *
 * Must run BEFORE the main esbuild bundle because esbuild reads
 * source-hash.ts at compile time. The previous implementation ran in
 * an onEnd hook which meant main.js always shipped the SHA of the
 * PREVIOUS build (or an empty string on a fresh checkout).
 */
async function generateSourceBundle() {
    const { createHash } = await import("crypto");
    const srcDir = join(__dirname, "src");
    const files = {};

    function walkDir(dir) {
        const entries = readdirSync(dir);
        for (const entry of entries) {
            const fullPath = join(dir, entry);
            const stat = statSync(fullPath);
            if (stat.isDirectory()) {
                if (entry === "node_modules" || entry === "__tests__" || entry === "test" || entry === "_generated") continue;
                walkDir(fullPath);
            } else if (entry.endsWith(".ts") || entry.endsWith(".tsx")) {
                const relPath = "src/" + relative(srcDir, fullPath).replace(/\\/g, "/");
                const content = readFileSync(fullPath, "utf-8");
                files[relPath] = Buffer.from(content).toString("base64");
            }
        }
    }
    walkDir(srcDir);

    const pkg = JSON.parse(readFileSync(join(__dirname, "package.json"), "utf-8"));
    const manifest = JSON.parse(readFileSync(join(__dirname, "manifest.json"), "utf-8"));
    const bundle = {
        version: manifest.version || pkg.version || "0.0.0",
        files,
        buildConfig: {
            format: "cjs",
            target: "es2022",
            external: [
                "obsidian", "electron",
                "@codemirror/autocomplete", "@codemirror/collab",
                "@codemirror/commands", "@codemirror/language",
                "@codemirror/lint", "@codemirror/search",
                "@codemirror/state", "@codemirror/view",
                "@lezer/common", "@lezer/highlight", "@lezer/lr",
            ],
        },
    };

    const json = JSON.stringify(bundle);
    writeFileSync(join(__dirname, "plugin-source.json"), json);

    const sha = createHash("sha256").update(json).digest("hex");
    const outDir = join(__dirname, "src/_generated");
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
    writeFileSync(
        join(outDir, "source-hash.ts"),
        "// AUTO-GENERATED -- do not edit. Source: esbuild generateSourceBundle().\n" +
        "/* eslint-disable */\n\n" +
        `export const SELF_DEV_SOURCE_SHA256 = "${sha}";\n`,
    );

    const fileCount = Object.keys(files).length;
    const sizeKB = Math.round(json.length / 1024);
    console.log(`[source-bundle] plugin-source.json: ${fileCount} files, ${sizeKB} KB, sha=${sha.slice(0, 16)}...`);
}

// Path to the Obsidian vault plugin folder (auto-deploy on build)
// Set PLUGIN_DIR in your .env or shell environment
// Load .env file if it exists (for PLUGIN_DIR with iCloud paths containing spaces)
try {
    const envContent = readFileSync(join(__dirname, '.env'), 'utf-8');
    for (const line of envContent.split('\n')) {
        const match = line.match(/^([A-Z_]+)=(.*)$/);
        if (match && !process.env[match[1]]) {
            // Strip surrounding quotes (single or double) from .env values
            process.env[match[1]] = match[2].trim().replace(/^["']|["']$/g, '');
        }
    }
} catch { /* .env not found — use shell environment */ }
const VAULT_PLUGIN_DIR = process.env.PLUGIN_DIR || "";

// Main context creation is deferred to after generateSourceBundle()
// runs, so esbuild reads the freshly written SHA from
// src/_generated/source-hash.ts instead of an empty placeholder.
const mainBuildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    // Minify on production only. Cuts main.js by 40-60 % which keeps it
    // closer to Obsidian Sync Standard's 5 MB ceiling without losing any
    // feature. Stack traces are minified too, but Obsidian users see
    // them as line:column references and we ship the source bundle as
    // an optional asset (plugin-source.json) for symbolicated debugging.
    minify: prod,
    outfile: "main.js",
    plugins: [
        {
            // Resolve "node:xyz" imports → mark them external (Electron provides them)
            name: "node-builtins",
            setup(build) {
                build.onResolve({ filter: /^node:/ }, (args) => ({
                    path: args.path,
                    external: true,
                }));
            }
        },
        {
            // Force transformers.js to use the web ONNX backend in Electron.
            // Electron's renderer is detected as IS_NODE_ENV=true, which selects
            // onnxruntime-node (native addon that can't load). Patching to false
            // makes it take the web branch with proper device registration.
            name: "force-onnx-web-backend",
            setup(build) {
                build.onResolve({ filter: /backends\/onnx\.js/ }, (args) => {
                    if (!args.path.includes('onnx')) return;
                    return { path: args.path, pluginData: { patch: true }, namespace: 'file' };
                });
                // Fallback: post-process the bundle to patch IS_NODE_ENV
                build.onEnd(() => {
                    const outfile = 'main.js';
                    if (!existsSync(outfile)) return;
                    let code = readFileSync(outfile, 'utf-8');
                    const marker = '} else if (apis.IS_NODE_ENV) {';
                    if (code.includes(marker)) {
                        code = code.replace(marker, '} else if (false /* patched: force web backend in Electron */) {');
                        writeFileSync(outfile, code);
                        console.log('[force-onnx-web-backend] Patched IS_NODE_ENV in main.js');
                    }
                });
            }
        },
        // emit-source-bundle was an esbuild plugin running in onEnd which
        // meant it wrote source-hash.ts AFTER main.js had already been
        // bundled. Result: main.js always contained the previous build's
        // SHA (or an empty string on the very first build), and
        // EmbeddedSourceManager rejected every freshly downloaded source
        // bundle as "hash mismatch". The bundle generation is now a
        // standalone function called BEFORE context.rebuild(); see
        // generateSourceBundle() at module scope and its invocation in
        // the prod / dev branches below.
        {
            name: "vault-deploy",
            setup(build) {
                build.onEnd(() => {
                    if (existsSync(VAULT_PLUGIN_DIR)) {
                        try {
                            // Only the three files Obsidian itself supports.
                            // All other assets (workers, WASM, skills, templates)
                            // are inlined into main.js by generateInlineAssets()
                            // and live in <vault>/.vault-operator/ at runtime.
                            copyFileSync("main.js", `${VAULT_PLUGIN_DIR}/main.js`);
                            copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
                            copyFileSync("manifest.json", `${VAULT_PLUGIN_DIR}/manifest.json`);
                            console.log(`[vault-deploy] → ${VAULT_PLUGIN_DIR}`);
                        } catch (e) {
                            console.warn("[vault-deploy] Copy failed:", e.message);
                        }
                    }
                });
            }
        }
    ],
};

// Sandbox worker — separate OS process (ADR-021)
const workerContext = await esbuild.context({
    entryPoints: ["src/core/sandbox/sandbox-worker.ts"],
    bundle: true,
    external: [],        // Standalone Node.js, no externals needed
    platform: "node",
    format: "cjs",
    target: "es2022",
    outfile: "sandbox-worker.js",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
});

// MCP Server worker — separate OS process (ADR-053)
const mcpWorkerContext = await esbuild.context({
    entryPoints: ["src/mcp/mcp-server-worker.ts"],
    bundle: true,
    external: [],        // Standalone Node.js, bundled with MCP SDK
    platform: "node",
    format: "cjs",
    target: "es2022",
    outfile: "mcp-server-worker.js",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
});

if (prod) {
    // Workers first — they get inlined into main.js via generateInlineAssets
    await workerContext.rebuild();
    await mcpWorkerContext.rebuild();
    // Emit src/_generated/bundled-*.ts files which the readers import.
    generateInlineAssets();
    // Emit plugin-source.json + source-hash.ts BEFORE the main esbuild
    // context is created so esbuild reads the freshly written SHA.
    await generateSourceBundle();
    // Single-shot build with up-to-date generated files
    await esbuild.build(mainBuildOptions);
    process.exit(0);
} else {
    try { generateInlineAssets(); } catch { /* workers not yet built — will be generated on first rebuild */ }
    try { await generateSourceBundle(); } catch { /* non-fatal during watch */ }
    const context = await esbuild.context(mainBuildOptions);
    await context.watch();
    await workerContext.watch();
    await mcpWorkerContext.watch();
}
